name: "wireit-setup-github-actions-caching"
author: "Google LLC"
description: "Enables Wireit's GitHub Actions caching mode and exposes required environment variables"
outputs:
  sample_output:
    description: "A sample output value"
runs:
  using: "node20"
  main: "index.js"
  post: "cleanup.js"
